# Generated by Django 3.2.14 on 2022-08-19 21:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/paulfitz85/image/upload/v1659219337/media/images/default_genre_photo_acacvw.jpg', max_length=255, verbose_name='image'),
        ),
    ]
