# Generated by Django 3.2.14 on 2022-08-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='next_gig',
            field=models.TextField(default='DD-MM-YYYY'),
        ),
    ]
