# Generated by Django 3.2.14 on 2022-07-25 18:49

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Genre_lite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_lite_name', models.CharField(max_length=200, unique=True)),
                ('slug_lite', models.SlugField(max_length=200, unique=True)),
                ('content_lite', models.TextField()),
                ('genre_lite_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('excerpt_lite', models.TextField(blank=True)),
                ('status_lite', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author_lite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_lite_section', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
