# Generated by Django 3.2.14 on 2022-07-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_auto_20220725_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
