# Generated by Django 3.2.14 on 2022-07-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_genre_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre_lite',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
