# Generated by Django 3.2.14 on 2022-07-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0004_genre_lite_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre_lite',
        ),
    ]
