# Generated by Django 3.2.14 on 2022-07-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0006_auto_20220730_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
