# Generated by Django 3.2.14 on 2022-07-30 19:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0007_band_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_image',
            field=cloudinary.models.CloudinaryField(default='/images/default-genre-photo.jpg', max_length=255, verbose_name='image'),
        ),
    ]
