# Generated by Django 3.2.14 on 2022-07-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0023_alter_band_band_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_image',
            field=models.ImageField(default='/images/default-genre-photo.jpg', upload_to='https://cloudinary.com/console/c-c24d22f1b451dca182670b2cf976ec/media_library/folders/c12896f112895c0f6e31ef0d8155d6ec0a'),
        ),
    ]
