# Generated by Django 3.2.14 on 2022-08-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0030_alter_band_band_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_image',
            field=models.ImageField(default='/images/default-genre-photo.jpg', upload_to='images'),
        ),
    ]
