# Generated by Django 3.2.14 on 2022-07-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='genre',
            new_name='band_title',
        ),
    ]
