# Generated by Django 3.2.14 on 2022-07-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_rename_genre_band_band_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='band_title',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='band',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
