# Generated by Django 3.2.14 on 2022-07-22 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genre', '0003_auto_20220722_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='profile_created_on',
        ),
        migrations.RemoveField(
            model_name='band',
            name='status',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_title',
        ),
        migrations.AddField(
            model_name='genre',
            name='created_on',
            field=models.DateTimeField(default='DEFAULT VALUE'),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
